site_name: Mobball-remake Docs
theme:
  name: material
  language: en
  logo: null
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - navigation.tabs
    - content.code.copy
  palette:
    - scheme: default
      primary: green
      accent: light green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: green
      accent: light green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences

plugins:
  - search:
      lang: ja
  - i18n:
      docs_structure: folder
      languages:
        - locale: ja
          name: 日本語
          build: true
          default: true
repo_url: https://github.com/morinoparty/Mobball-remake
repo_name: Mobball-remake
copyright: No Rights Reserved(CC0).  Written by Nikomaru in 2024